### ISSUE TITLE
Problem with WebChat.lua

### ISSUE THREAD

**Issue by goopsie** [goopsie/PPCHAT#2]
it's pure trash

**Comment by goopsie** [comment]
kind of fixed it, still pretty bad. no comments or anything

**Comment by goopsie** [comment]
added comments

**Comment by goopsie** [comment]
POTENTIAL FIX DISCOVERED; MINIMIZE CODE.

**Comment by UlisseMini** [comment]
we wont be fixing this because we have more importent things to do, like write *lExIcAl pArSeR cOmBiNaToRs*
